# Usage
# Start: docker compose -f docker-compose.dev.yml up -d
# Stop: docker compose -f docker-compose.dev.yml down
# Destroy: docker compose -f docker-compose.dev.yml down -v --remove-orphans
# Remove volumes: docker volume rm votewise_db votewise_redis uploads

name: votewise

services:
  postgres:
    image: postgres:16.3-alpine
    container_name: votewise_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5450:5432"
    volumes:
      - votewise_db:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    container_name: votewise_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - votewise_redis:/data

  mailhog:
    image: mailhog/mailhog
    container_name: votewise_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  nginx:
    image: nginx:alpine
    container_name: votewise_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  votewise_db:
  votewise_redis:
  uploads:
